---
version: "3.9"
services:
 devopsdb:
   image: krishn23/manual:db
   ports:
     - "3306:3306"
   networks:
     - mynetwork
   volumes:
     - db_data:/var/lib/mysql

 application:
   image: shaikmustafa/harikanew:appimage
   ports:
     - "1111:8080"
   depends_on:
     - "devopsdb"
   networks:
     - mynetwork

networks:
  mynetwork:
    driver: overlay

volumes:
  db_data:


